import { createApp } from "vue";
import Main from "./Main.vue";
import router from "@/router/index";
import { createPinia } from "pinia";
const pinia = createPinia();
const app = createApp(Main);
app.use(router);
app.use(pinia);
app.mount("#Main");
export default app;
